### ISSUE TITLE
I can’t see the map

### ISSUE THREAD

**Issue by assoscoupa** [lriaudel/cpt-to-map-store#1]
I have installed ACF Pro and ACF OpenStreetMap Field.

I have also installed the Custom Post Type to Map Store 🙂

I have gone through two points and I see that you are creating the json code as follows:

https://beta01.listedbuildings.eu/wp-json/cpt_to_map_store/building/

{“type”:”FeatureCollection”,”features”:[{“type”:”Feature”,”id”:21,”geometry”:{“type”:”Point”,”coordinates”:[23.728954600000002,37.981781599999998]},”properties”:{“name”:”\u039a\u03b5\u03bd\u03c4\u03c1\u03b9\u03ba\u03cc \u03ba\u03c4\u03ae\u03c1\u03b9\u03bf \u0395\u03b8\u03bd\u03b9\u03ba\u03ae\u03c2 \u03a4\u03c1\u03ac\u03c0\u03b5\u03b6\u03b1\u03c2″,”description”:”1840″,”bindPopup_content”:””},”title”:”\u039a\u03b5\u03bd\u03c4\u03c1\u03b9\u03ba\u03cc \u03ba\u03c4\u03ae\u03c1\u03b9\u03bf \u0395\u03b8\u03bd\u03b9\u03ba\u03ae\u03c2 \u03a4\u03c1\u03ac\u03c0\u03b5\u03b6\u03b1\u03c2″},{“type”:”Feature”,”id”:14,”geometry”:{“type”:”Point”,”coordinates”:[23.737021299999999,37.9753221]},”properties”:{“name”:”\u0392\u03bf\u03c5\u03bb\u03ae \u03c4\u03c9\u03bd \u0395\u03bb\u03bb\u03ae\u03bd\u03c9\u03bd”,”description”:”1836″,”bindPopup_content”:””},”title”:”\u0392\u03bf\u03c5\u03bb\u03ae \u03c4\u03c9\u03bd \u0395\u03bb\u03bb\u03ae\u03bd\u03c9\u03bd”}]}

First of all, let me note that
the first point has coordinates: lat:37.9817816 & lng: 23.7289546
https://beta01.listedbuildings.eu/building/nbg-headquarters/

and my second point lat: 37.9753221& lng: 23.7370213
https://beta01.listedbuildings.eu/building/vouli-ton-ellinon/

while in json they appear upside down !!!

I add the shortcode “[map_store]” to the following post and see only one blank space.
https://beta01.listedbuildings.eu/uncategorized/test01-post/

This is screenshot from my settings 

![CPT_to_Map_Store2](https://user-images.githubusercontent.com/11008902/84310529-79688f00-ab6a-11ea-9ebb-20258efea897.png)

**Comment by lriaudel** [comment]
Hi,
For the coordinate 
https://tools.ietf.org/html/rfc7946#section-3.1.1
![image](https://user-images.githubusercontent.com/4172532/84506038-015fad80-acbf-11ea-85e6-5948149cc76c.png)

**Comment by lriaudel** [comment]
For this URL : https://beta01.listedbuildings.eu/uncategorized/test01-post/

The script or not loaded.

Did you change anything in the script enqueue ?

**Comment by assoscoupa** [comment]
> Did you change anything in the script enqueue ?

Thanks for answer.
No, I haven't changed anything.

**Comment by lriaudel** [comment]
The script is : `http://exemple.local/wp-content/plugins/cpt-to-map-store/assets/js/public.js`

**Comment by lriaudel** [comment]
Okay, there's a problem.
I see the week end.
Thanks

**Comment by lriaudel** [comment]
Thanks for your help.
I don't see this enormous error !

**Comment by lriaudel** [comment]
I update the repository on wp.org

**Comment by assoscoupa** [comment]
oh! Thank you.
