### ISSUE TITLE
The photos does not appear in the pin popup

### ISSUE THREAD

**Issue by assoscoupa** [lriaudel/cpt-to-map-store#2]
I have a custom field for photography in my installation which I call "photo".

When I enter the {photo} in the Template popup, then the only thing that returns is the id attachment.

The Template popup does not accept php code to write dynamically.

What is the solution?

Thanks!

**Comment by lriaudel** [comment]
Hi,

Do you want a filter to customize the marker ?

![image](https://user-images.githubusercontent.com/4172532/84699862-94fcdc80-af52-11ea-9b7b-22a6719d9aff.png)

**Comment by lriaudel** [comment]
Here the code to hook in 1.0.3 version: 
```
function bindPopup_content_filter( $bindPopup_content, $post_id ) {
	return "Yeahhhhh";
}
add_filter( 'cpt_to_map_store_bindPopup_content', 'bindPopup_content_filter', 10, 2 );
```

**Comment by lriaudel** [comment]
@assoscoupa It is ok for you ?

**Comment by assoscoupa** [comment]
I put your code to the test and it worked fine.

But I didn't manage to show my own field.

Could you give me a code example of how I should write it so that I can display, for example, my own field called "property_status" ?

**Comment by assoscoupa** [comment]
It is also possible to disable the rolling wheel zoom on the map?

**Comment by lriaudel** [comment]
In this filter, you can put your code to get the different fields :
ACF : https://www.advancedcustomfields.com/resources/get_field/
WP : https://developer.wordpress.org/reference/functions/get_post_meta/
And generate your own template

**Comment by lriaudel** [comment]
For the wheel, can you open a other issue ?
Have you an example ?
